# Generated by Django 5.0.1 on 2024-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='estado',
        ),
        migrations.AddField(
            model_name='noticia',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
