# Generated by Django 5.0.6 on 2024-05-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodista',
            name='Imagen_Perfil',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
